/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedNouvelleCommandeRouteImport } from './routes/_authenticated/nouvelle-commande'
import { Route as AuthenticatedArticlesRouteImport } from './routes/_authenticated/articles'
import { Route as AuthenticatedCommandesIndexRouteImport } from './routes/_authenticated/commandes.index'
import { Route as AuthenticatedCommandesIdRouteImport } from './routes/_authenticated/commandes.$id'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNouvelleCommandeRoute =
  AuthenticatedNouvelleCommandeRouteImport.update({
    id: '/_authenticated/nouvelle-commande',
    path: '/nouvelle-commande',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedArticlesRoute = AuthenticatedArticlesRouteImport.update({
  id: '/_authenticated/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCommandesIndexRoute =
  AuthenticatedCommandesIndexRouteImport.update({
    id: '/_authenticated/commandes/',
    path: '/commandes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCommandesIdRoute =
  AuthenticatedCommandesIdRouteImport.update({
    id: '/_authenticated/commandes/$id',
    path: '/commandes/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/articles': typeof AuthenticatedArticlesRoute
  '/nouvelle-commande': typeof AuthenticatedNouvelleCommandeRoute
  '/': typeof AuthenticatedIndexRoute
  '/commandes/$id': typeof AuthenticatedCommandesIdRoute
  '/commandes/': typeof AuthenticatedCommandesIndexRoute
}
export interface FileRoutesByTo {
  '/articles': typeof AuthenticatedArticlesRoute
  '/nouvelle-commande': typeof AuthenticatedNouvelleCommandeRoute
  '/': typeof AuthenticatedIndexRoute
  '/commandes/$id': typeof AuthenticatedCommandesIdRoute
  '/commandes': typeof AuthenticatedCommandesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/articles': typeof AuthenticatedArticlesRoute
  '/_authenticated/nouvelle-commande': typeof AuthenticatedNouvelleCommandeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/commandes/$id': typeof AuthenticatedCommandesIdRoute
  '/_authenticated/commandes/': typeof AuthenticatedCommandesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/articles'
    | '/nouvelle-commande'
    | '/'
    | '/commandes/$id'
    | '/commandes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/articles' | '/nouvelle-commande' | '/' | '/commandes/$id' | '/commandes'
  id:
    | '__root__'
    | '/_authenticated/articles'
    | '/_authenticated/nouvelle-commande'
    | '/_authenticated/'
    | '/_authenticated/commandes/$id'
    | '/_authenticated/commandes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedArticlesRoute: typeof AuthenticatedArticlesRoute
  AuthenticatedNouvelleCommandeRoute: typeof AuthenticatedNouvelleCommandeRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCommandesIdRoute: typeof AuthenticatedCommandesIdRoute
  AuthenticatedCommandesIndexRoute: typeof AuthenticatedCommandesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/nouvelle-commande': {
      id: '/_authenticated/nouvelle-commande'
      path: '/nouvelle-commande'
      fullPath: '/nouvelle-commande'
      preLoaderRoute: typeof AuthenticatedNouvelleCommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/articles': {
      id: '/_authenticated/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof AuthenticatedArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/commandes/': {
      id: '/_authenticated/commandes/'
      path: '/commandes'
      fullPath: '/commandes/'
      preLoaderRoute: typeof AuthenticatedCommandesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/commandes/$id': {
      id: '/_authenticated/commandes/$id'
      path: '/commandes/$id'
      fullPath: '/commandes/$id'
      preLoaderRoute: typeof AuthenticatedCommandesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedArticlesRoute: AuthenticatedArticlesRoute,
  AuthenticatedNouvelleCommandeRoute: AuthenticatedNouvelleCommandeRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCommandesIdRoute: AuthenticatedCommandesIdRoute,
  AuthenticatedCommandesIndexRoute: AuthenticatedCommandesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
