/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedNouvelleCommandeRouteImport } from './routes/_authenticated/nouvelle-commande'
import { Route as AuthenticatedArticlesRouteImport } from './routes/_authenticated/articles'
import { Route as AuthenticatedCommandesIndexRouteImport } from './routes/_authenticated/commandes.index'
import { Route as AuthenticatedCommandesIdRouteImport } from './routes/_authenticated/commandes.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNouvelleCommandeRoute =
  AuthenticatedNouvelleCommandeRouteImport.update({
    id: '/nouvelle-commande',
    path: '/nouvelle-commande',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedArticlesRoute = AuthenticatedArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommandesIndexRoute =
  AuthenticatedCommandesIndexRouteImport.update({
    id: '/commandes/',
    path: '/commandes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommandesIdRoute =
  AuthenticatedCommandesIdRouteImport.update({
    id: '/commandes/$id',
    path: '/commandes/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/articles': typeof AuthenticatedArticlesRoute
  '/nouvelle-commande': typeof AuthenticatedNouvelleCommandeRoute
  '/commandes/$id': typeof AuthenticatedCommandesIdRoute
  '/commandes/': typeof AuthenticatedCommandesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/articles': typeof AuthenticatedArticlesRoute
  '/nouvelle-commande': typeof AuthenticatedNouvelleCommandeRoute
  '/': typeof AuthenticatedIndexRoute
  '/commandes/$id': typeof AuthenticatedCommandesIdRoute
  '/commandes': typeof AuthenticatedCommandesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/articles': typeof AuthenticatedArticlesRoute
  '/_authenticated/nouvelle-commande': typeof AuthenticatedNouvelleCommandeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/commandes/$id': typeof AuthenticatedCommandesIdRoute
  '/_authenticated/commandes/': typeof AuthenticatedCommandesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/articles'
    | '/nouvelle-commande'
    | '/commandes/$id'
    | '/commandes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/articles'
    | '/nouvelle-commande'
    | '/'
    | '/commandes/$id'
    | '/commandes'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/articles'
    | '/_authenticated/nouvelle-commande'
    | '/_authenticated/'
    | '/_authenticated/commandes/$id'
    | '/_authenticated/commandes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nouvelle-commande': {
      id: '/_authenticated/nouvelle-commande'
      path: '/nouvelle-commande'
      fullPath: '/nouvelle-commande'
      preLoaderRoute: typeof AuthenticatedNouvelleCommandeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/articles': {
      id: '/_authenticated/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof AuthenticatedArticlesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/commandes/': {
      id: '/_authenticated/commandes/'
      path: '/commandes'
      fullPath: '/commandes/'
      preLoaderRoute: typeof AuthenticatedCommandesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/commandes/$id': {
      id: '/_authenticated/commandes/$id'
      path: '/commandes/$id'
      fullPath: '/commandes/$id'
      preLoaderRoute: typeof AuthenticatedCommandesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedArticlesRoute: typeof AuthenticatedArticlesRoute
  AuthenticatedNouvelleCommandeRoute: typeof AuthenticatedNouvelleCommandeRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCommandesIdRoute: typeof AuthenticatedCommandesIdRoute
  AuthenticatedCommandesIndexRoute: typeof AuthenticatedCommandesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedArticlesRoute: AuthenticatedArticlesRoute,
  AuthenticatedNouvelleCommandeRoute: AuthenticatedNouvelleCommandeRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCommandesIdRoute: AuthenticatedCommandesIdRoute,
  AuthenticatedCommandesIndexRoute: AuthenticatedCommandesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
